### ISSUE TITLE
copy fix: Connect Twitter flow UI still refers to Autism instead of Zkitter

### ISSUE THREAD

**Issue by 0xtsukino** [zkitter/ui#45]
use short name from `process.env.MANIFEST` (it points to a json file)

**Let's hardcode if it takes more than 5 minute to figure out how to use shortname**

**Comment by r1oga** [comment]
See `manifest.short_name`
https://github.com/zkitter/ui/blob/a70fa81c18fda1a176dc31c180041846f9a037e5/static/manifest.zkitter.json#L3
